### ISSUE TITLE
project clean up request

### ISSUE THREAD

**Issue by kurdbohu** [agosdahu/Led_Project#15]
Hi,

please remove following branches, because they are outdated and will never be used anymore:
- master-please-merge-ASAP
- kurdbohu-patch-1
- kurdbohu (i'm going to create a new branch from master)

The corresponding Pull request shall be removed, too:
- Led Handler improved (?), some clean ups

Thanks,
Bogdán

**Comment by agosdahu** [comment]
Hi, sorry for the tardyness in my activity, I spent a good amount of my weekend painting wooden fences at my parent's.

I'll check the rest of the project and any further developments from this moment on

**Comment by agosdahu** [comment]
Done

**Comment by kurdbohu** [comment]
Köszi! :)
