### ISSUE TITLE
suggestion for using non-built-in types

### ISSUE THREAD

**Issue by kurdbohu** [agosdahu/Led_Project#17]
You can use the following definitions without adding any header file to project:
- typedef signed char **int8_t**;
- typedef unsigned char **uint8_t**;
- typedef signed int **int16_t**;
- typedef unsigned int **uint16_t**;
- typedef signed long int **int32_t**;
- typedef unsigned long int **uint32_t**;
- typedef signed long long int **int64_t**;
- typedef unsigned long long int **uint64_t**;

They are defined in c:\program files\arduino\hardware\tools\avr\avr\include\stdint.h.
Using these types is highly recommended, since built-in types are hardware-dependent.

**Comment by agosdahu** [comment]
Good finding
👍
